/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Management;

import java.awt.Color;
import java.awt.Image;
import java.util.Stack;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KAMRAN TECH
 */
public class Office_Management_System extends javax.swing.JFrame {

    public Office_Manager office1;
    
        //Main  banner
        public void Bannerimg()
    {
        ImageIcon icon = new ImageIcon("C:\\Users\\KAMRAN TECH\\Documents\\NetBeansProjects\\Office Management System\\src\\images/bg.png");
        Image img =icon.getImage();
        Image imgscl = img.getScaledInstance(jLabel16.getWidth(), jLabel16.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon sclit = new ImageIcon(imgscl);
        jLabel16.setIcon(sclit);
    }

    public Office_Management_System() {
        initComponents();
        office1 = new Office_Manager();
        //Banner
        Bannerimg();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        try {
            jLabel2 =(javax.swing.JLabel)java.beans.Beans.instantiate(getClass().getClassLoader(), "Management.J2_jLabel2");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Hiddenpannel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jLabel88 = new javax.swing.JLabel();
        Employeid = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel91 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jTextField3 = new javax.swing.JTextField();
        jLabel92 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jTextField4 = new javax.swing.JTextField();
        jLabel93 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jTextField5 = new javax.swing.JTextField();
        jLabel94 = new javax.swing.JLabel();
        EmployeeAdd = new javax.swing.JButton();
        EmployeeUpdate = new javax.swing.JButton();
        EmployeeDelete = new javax.swing.JButton();
        jLabel52 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel70 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jLabel89 = new javax.swing.JLabel();
        Staffid = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel95 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jTextField7 = new javax.swing.JTextField();
        jLabel96 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jTextField8 = new javax.swing.JTextField();
        jLabel97 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jTextField9 = new javax.swing.JTextField();
        jLabel98 = new javax.swing.JLabel();
        StaffAdd = new javax.swing.JButton();
        StaffUpdate = new javax.swing.JButton();
        StaffDelete = new javax.swing.JButton();
        jLabel53 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel71 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jLabel90 = new javax.swing.JLabel();
        peonid = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel99 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jTextField11 = new javax.swing.JTextField();
        jLabel100 = new javax.swing.JLabel();
        jSeparator21 = new javax.swing.JSeparator();
        jTextField12 = new javax.swing.JTextField();
        jLabel101 = new javax.swing.JLabel();
        jSeparator22 = new javax.swing.JSeparator();
        jTextField13 = new javax.swing.JTextField();
        jLabel102 = new javax.swing.JLabel();
        PeonAdd = new javax.swing.JButton();
        PeonUpdate = new javax.swing.JButton();
        PeonDelete = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel72 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        temp = new javax.swing.JTextField();
        temp1 = new javax.swing.JTextField();
        temp2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(57, 51, 51));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255,80));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 6, -1, -1));
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 67, 141, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 93, 268, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" WELCOME ADMIN");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 150, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-male-user-55.png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 60, 60));

        jLabel8.setBackground(new java.awt.Color(57, 51, 51));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-30.png"))); // NOI18N
        jLabel8.setText("LOGOUT");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 150, 50));

        jLabel9.setBackground(new java.awt.Color(57, 51, 51));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-system-task-30.png"))); // NOI18N
        jLabel9.setText(" Dashboard");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 150, 50));

        jLabel11.setBackground(new java.awt.Color(57, 51, 51));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-30.png"))); // NOI18N
        jLabel11.setText(" Employee");
        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 150, 50));

        jLabel12.setBackground(new java.awt.Color(57, 51, 51));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-30.png"))); // NOI18N
        jLabel12.setText("Staff");
        jLabel12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 150, 50));

        jLabel10.setBackground(new java.awt.Color(57, 51, 51));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-30.png"))); // NOI18N
        jLabel10.setText("Peon");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 150, 50));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 630));

        Hiddenpannel.setBackground(new java.awt.Color(102, 102, 102));
        Hiddenpannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Office Management System");
        Hiddenpannel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 448, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-close-35.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        Hiddenpannel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, 40, 30));

        jPanel1.add(Hiddenpannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1060, 50));

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel7.setLayout(null);

        jLabel16.setText("jLabel16");
        jPanel7.add(jLabel16);
        jLabel16.setBounds(-12, 18, 1070, 590);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("dash", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel40.setBackground(new java.awt.Color(255, 255, 255));
        jPanel40.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel40.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel88.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel88.setText("Employee ID:");
        jPanel40.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 123, 90, -1));

        Employeid.setBorder(null);
        jPanel40.add(Employeid, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 117, 110, -1));
        jPanel40.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 145, 75, 10));
        jPanel40.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 161, 1210, 10));

        jLabel91.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel91.setText("Name");
        jPanel40.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jTextField2.setBorder(null);
        jPanel40.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 334, -1));
        jPanel40.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 334, 10));
        jPanel40.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 334, 10));

        jTextField3.setBorder(null);
        jPanel40.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 334, -1));

        jLabel92.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel92.setText("Mobile Number");
        jPanel40.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        jPanel40.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 334, 10));

        jTextField4.setBorder(null);
        jPanel40.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 334, -1));

        jLabel93.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel93.setText("Qualification");
        jPanel40.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));
        jPanel40.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 334, 10));

        jTextField5.setBorder(null);
        jPanel40.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 334, -1));

        jLabel94.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel94.setText("Experience");
        jPanel40.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        EmployeeAdd.setBackground(new java.awt.Color(51, 255, 51));
        EmployeeAdd.setForeground(new java.awt.Color(255, 255, 255));
        EmployeeAdd.setText("ADD");
        EmployeeAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmployeeAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeAddActionPerformed(evt);
            }
        });
        jPanel40.add(EmployeeAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 120, 30));

        EmployeeUpdate.setBackground(new java.awt.Color(255, 51, 51));
        EmployeeUpdate.setForeground(new java.awt.Color(255, 255, 255));
        EmployeeUpdate.setText("UPDATE");
        EmployeeUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmployeeUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeUpdateActionPerformed(evt);
            }
        });
        jPanel40.add(EmployeeUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 120, 30));

        EmployeeDelete.setBackground(new java.awt.Color(0, 0, 0));
        EmployeeDelete.setForeground(new java.awt.Color(255, 255, 255));
        EmployeeDelete.setText("DELETE");
        EmployeeDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmployeeDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeDeleteActionPerformed(evt);
            }
        });
        jPanel40.add(EmployeeDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 110, 30));

        jLabel52.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-employee-50.png"))); // NOI18N
        jLabel52.setText("EMPLOYEE");
        jPanel40.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 330, -1));

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel40.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 110, -1, -1));

        jLabel70.setText("Back");
        jLabel70.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel70.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel70MouseClicked(evt);
            }
        });
        jPanel40.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, -1, -1));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Phone", "Qualification", "Experince"
            }
        ));
        table1.setGridColor(new java.awt.Color(102, 102, 102));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        jPanel40.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 610, 300));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-back-45.png"))); // NOI18N
        jLabel7.setText("BACK");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel40.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, -1));

        jPanel8.add(jPanel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 600));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        jTabbedPane1.addTab("emp", jPanel3);

        jPanel41.setBackground(new java.awt.Color(255, 255, 255));
        jPanel41.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel89.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel89.setText("Staff ID:");
        jPanel41.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 123, 80, -1));

        Staffid.setBorder(null);
        jPanel41.add(Staffid, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 117, 78, -1));
        jPanel41.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 145, 75, 10));
        jPanel41.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 161, 1210, 10));

        jLabel95.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel95.setText("Name");
        jPanel41.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jTextField6.setBorder(null);
        jPanel41.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 334, -1));
        jPanel41.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 334, 10));
        jPanel41.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 334, 10));

        jTextField7.setBorder(null);
        jPanel41.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 334, -1));

        jLabel96.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel96.setText("Mobile Number");
        jPanel41.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        jPanel41.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 334, 10));

        jTextField8.setBorder(null);
        jPanel41.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 334, -1));

        jLabel97.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel97.setText("Salary");
        jPanel41.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));
        jPanel41.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 334, 10));

        jTextField9.setBorder(null);
        jPanel41.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 334, -1));

        jLabel98.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel98.setText("CNIC");
        jPanel41.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        StaffAdd.setBackground(new java.awt.Color(51, 255, 51));
        StaffAdd.setForeground(new java.awt.Color(255, 255, 255));
        StaffAdd.setText("ADD");
        StaffAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StaffAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffAddActionPerformed(evt);
            }
        });
        jPanel41.add(StaffAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 120, 30));

        StaffUpdate.setBackground(new java.awt.Color(255, 51, 51));
        StaffUpdate.setForeground(new java.awt.Color(255, 255, 255));
        StaffUpdate.setText("UPDATE");
        StaffUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StaffUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffUpdateActionPerformed(evt);
            }
        });
        jPanel41.add(StaffUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 120, 30));

        StaffDelete.setBackground(new java.awt.Color(0, 0, 0));
        StaffDelete.setForeground(new java.awt.Color(255, 255, 255));
        StaffDelete.setText("DELETE");
        StaffDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StaffDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffDeleteActionPerformed(evt);
            }
        });
        jPanel41.add(StaffDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 110, 30));

        jLabel53.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-staff-50.png"))); // NOI18N
        jLabel53.setText("STAFF");
        jPanel41.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel41.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 110, -1, -1));

        jLabel71.setText("Back");
        jLabel71.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel71.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel71MouseClicked(evt);
            }
        });
        jPanel41.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, -1, -1));

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Phone", "Salary", "CNIC"
            }
        ));
        table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table2);

        jPanel41.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 610, 300));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-back-45.png"))); // NOI18N
        jLabel13.setText("BACK");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel41.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, -1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel41, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("staf", jPanel5);

        jPanel42.setBackground(new java.awt.Color(255, 255, 255));
        jPanel42.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel42.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel90.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel90.setText("Peon ID:");
        jPanel42.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 123, 80, -1));

        peonid.setBorder(null);
        jPanel42.add(peonid, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 117, 78, -1));
        jPanel42.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 145, 75, 10));
        jPanel42.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 161, 1210, 10));

        jLabel99.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel99.setText("Name");
        jPanel42.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jTextField10.setBorder(null);
        jPanel42.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 334, -1));
        jPanel42.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 334, 10));
        jPanel42.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 334, 10));

        jTextField11.setBorder(null);
        jPanel42.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 334, -1));

        jLabel100.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel100.setText("Age");
        jPanel42.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        jPanel42.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 334, 10));

        jTextField12.setBorder(null);
        jPanel42.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 334, -1));

        jLabel101.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel101.setText("Salary");
        jPanel42.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));
        jPanel42.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 334, 10));

        jTextField13.setBorder(null);
        jPanel42.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 334, -1));

        jLabel102.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel102.setText("CNIC");
        jPanel42.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        PeonAdd.setBackground(new java.awt.Color(51, 255, 51));
        PeonAdd.setForeground(new java.awt.Color(255, 255, 255));
        PeonAdd.setText("ADD");
        PeonAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PeonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeonAddActionPerformed(evt);
            }
        });
        jPanel42.add(PeonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 120, 30));

        PeonUpdate.setBackground(new java.awt.Color(255, 51, 51));
        PeonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        PeonUpdate.setText("UPDATE");
        PeonUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PeonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeonUpdateActionPerformed(evt);
            }
        });
        jPanel42.add(PeonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 120, 30));

        PeonDelete.setBackground(new java.awt.Color(0, 0, 0));
        PeonDelete.setForeground(new java.awt.Color(255, 255, 255));
        PeonDelete.setText("DELETE");
        PeonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PeonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeonDeleteActionPerformed(evt);
            }
        });
        jPanel42.add(PeonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 110, 30));

        jLabel54.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-broom-50.png"))); // NOI18N
        jLabel54.setText("PEON");
        jPanel42.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel42.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 110, -1, -1));

        jLabel72.setText("Back");
        jLabel72.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel72.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel72MouseClicked(evt);
            }
        });
        jPanel42.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, -1, -1));

        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Age", "Salary", "CNIC"
            }
        ));
        table3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table3);

        jPanel42.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 610, 300));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-back-45.png"))); // NOI18N
        jLabel6.setText("BACK");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel42.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, -1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel42, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("peo", jPanel6);

        temp.setText("jTextField1");

        temp1.setText("jTextField1");

        temp2.setText("jTextField1");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(temp2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(temp, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                        .addComponent(temp1)))
                .addContainerGap(855, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(temp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(temp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(temp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(440, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab5", jPanel9);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1060, 630));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
//        jTabbedPane3.setSelectedIndex(0);

    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        // TODO add your handling code here:
        jLabel8.setBackground(Color.white);
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        // TODO add your handling code here:
        jLabel8.setBackground(Color.darkGray);
//        jLabel8.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        // TODO add your handling code here:
        jLabel9.setBackground(Color.white);
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        // TODO add your handling code here:
        jLabel9.setBackground(Color.darkGray);
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        // TODO add your handling code here:
        jLabel11.setBackground(Color.white);
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        // TODO add your handling code here:
        jLabel11.setBackground(Color.darkGray);
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        // TODO add your handling code here:
        jLabel12.setBackground(Color.white);
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        // TODO add your handling code here:
        jLabel12.setBackground(Color.darkGray);
    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
             new Login_system().setVisible(true);
           setVisible(false);
//        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        //mobile number Search

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jLabel70MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel70MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel70MouseClicked

    private void EmployeeAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeAddActionPerformed
        int id = Integer.parseInt(Employeid.getText());
        String name = jTextField2.getText();
        String phone = jTextField3.getText();
        String qual = jTextField4.getText();
        String exp = jTextField5.getText();
        String cnic = temp.getText();
        String salary = temp.getText();
        String age = temp.getText();

        Office off = new Office(id, name, phone, qual, exp, cnic, salary, age);
        office1.add(off);
//        Data Push To Table
        DefaultTableModel tblmodel = (DefaultTableModel) table1.getModel();
        ((DefaultTableModel) table1.getModel()).setNumRows(0);
        tblmodel.setRowCount(0); // Clear existing data

        Stack<Office> emp = office1.getAlldata();
        for (Office office : emp) {
            Object[] rowData = {office.getId(), office.getName(), office.getPhone(), office.getQual(), office.getExp()};
            tblmodel.addRow(rowData);
        }
//        For clear all fiels
        Employeid.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        JOptionPane.showMessageDialog(this, "Data Successfully Added");
        
        
        

    }//GEN-LAST:event_EmployeeAddActionPerformed

    private void EmployeeDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = table1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to remove.");
            return;
        }

        int id = (int) table1.getValueAt(selectedRow, 0);
        office1.remove(id);
//        Data Push To Table
        DefaultTableModel tblmodel = (DefaultTableModel) table1.getModel();
        ((DefaultTableModel) table1.getModel()).setNumRows(0);
        tblmodel.setRowCount(0); // Clear existing data

        Stack<Office> emp = office1.getAlldata();
        for (Office office : emp) {
            Object[] rowData = {office.getId(), office.getName(), office.getPhone(), office.getQual(), office.getExp()};
            tblmodel.addRow(rowData);
        }
//        For clear all fiels
        Employeid.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        JOptionPane.showMessageDialog(this, "Data Successfully Deleted");
    }//GEN-LAST:event_EmployeeDeleteActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        // TODO add your handling code here:
        jLabel10.setBackground(Color.white);
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        // TODO add your handling code here:
        jLabel10.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_jLabel10MouseExited

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        int selectedRow = table1.getSelectedRow();
        if (selectedRow != -1) {
            int id = (int) table1.getValueAt(selectedRow, 0);
            String name = (String) table1.getValueAt(selectedRow, 1);
            String phone = (String) table1.getValueAt(selectedRow, 2);
            String qual = (String) table1.getValueAt(selectedRow, 3);
            String exp = (String) table1.getValueAt(selectedRow, 4);

            Employeid.setText(String.valueOf(id));
            jTextField2.setText(name);
            jTextField3.setText(phone);
            jTextField4.setText(qual);
            jTextField5.setText(exp);
        }
    }//GEN-LAST:event_table1MouseClicked

    private void EmployeeUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRow = table1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to update.");
            return;
        }
        int id = (int) table1.getValueAt(selectedRow, 0);
//      int id = Integer.parseInt(Employeid.getText());
        String name = jTextField2.getText();
        String phone = jTextField3.getText();
        String qual = jTextField4.getText();
        String exp = jTextField5.getText();
        String cnic = temp.getText();
        String salary = temp.getText();
        String age = temp.getText();

        Office updatedoff = new Office(id, name, phone, qual, exp, cnic, salary, age);
        office1.update(id, updatedoff);
//        Data Push To Table
         DefaultTableModel tblmodel = (DefaultTableModel) table1.getModel();
        ((DefaultTableModel) table1.getModel()).setNumRows(0);
        tblmodel.setRowCount(0); // Clear existing data

        Stack<Office> emp = office1.getAlldata();
        for (Office office : emp) {
            Object[] rowData = {office.getId(), office.getName(), office.getPhone(), office.getQual(), office.getExp()};
            tblmodel.addRow(rowData);
        }
//        For clear all fiels
        Employeid.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        JOptionPane.showMessageDialog(this, "Data Successfully Updated");
    }//GEN-LAST:event_EmployeeUpdateActionPerformed

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jLabel71MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel71MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel71MouseClicked

    private void StaffAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffAddActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(Staffid.getText());
        String name = jTextField6.getText();
        String phone = jTextField7.getText();
        String qual = temp1.getText();
        String exp = temp1.getText();
        String cnic = jTextField9.getText();
        String salary = jTextField8.getText();
        String age = temp1.getText();

        Office off = new Office(id, name, phone, qual, exp, cnic, salary, age);
        office1.add(off);
//        Data Push To Table
        DefaultTableModel tblmodel = (DefaultTableModel) table2.getModel();
        ((DefaultTableModel) table2.getModel()).setNumRows(0);
        tblmodel.setRowCount(0); // Clear existing data

        Stack<Office> emp = office1.getAlldata();
        for (Office office : emp) {
            Object[] rowData = {office.getId(), office.getName(), office.getPhone(),office.getSalary(),office.getCnic()};
            tblmodel.addRow(rowData);
        }
//        For clear all fiels
        Staffid.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        JOptionPane.showMessageDialog(this, "Data Successfully Added");
    }//GEN-LAST:event_StaffAddActionPerformed

    private void StaffUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRow = table2.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to update.");
            return;
        }
        int id = (int) table2.getValueAt(selectedRow, 0);
//      int id = Integer.parseInt(Employeid.getText());
        String name = jTextField6.getText();
        String phone = jTextField7.getText();
        String qual = temp1.getText();
        String exp = temp1.getText();
        String cnic = jTextField9.getText();
        String salary = jTextField8.getText();
        String age = temp1.getText();

        Office updatedoff = new Office(id, name, phone, qual, exp, cnic, salary, age);
        office1.update(id, updatedoff);
//        Data Push To Table
         DefaultTableModel tblmodel = (DefaultTableModel) table2.getModel();
        ((DefaultTableModel) table2.getModel()).setNumRows(0);
        tblmodel.setRowCount(0); // Clear existing data

        Stack<Office> emp = office1.getAlldata();
        for (Office office : emp) {
            Object[] rowData = {office.getId(), office.getName(), office.getPhone(),office.getSalary(),office.getCnic()};
            tblmodel.addRow(rowData);
        }
//        For clear all fiels
        Staffid.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        JOptionPane.showMessageDialog(this, "Data Successfully Updated");
    }//GEN-LAST:event_StaffUpdateActionPerformed

    private void table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MouseClicked
        // TODO add your handling code here:
        int selectedRow = table2.getSelectedRow();
        if (selectedRow != -1) {
            int id = (int) table2.getValueAt(selectedRow, 0);
            String name = (String) table2.getValueAt(selectedRow, 1);
            String phone = (String) table2.getValueAt(selectedRow, 2);
            String salary = (String) table2.getValueAt(selectedRow, 3);
            String cnic = (String) table2.getValueAt(selectedRow, 4);

            Staffid.setText(String.valueOf(id));
            jTextField6.setText(name);
            jTextField7.setText(phone);
            jTextField8.setText(salary);
            jTextField9.setText(cnic);
        }
    }//GEN-LAST:event_table2MouseClicked

    private void StaffDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = table2.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to remove.");
            return;
        }

        int id = (int) table2.getValueAt(selectedRow, 0);
        office1.remove(id);
//        Data Push To Table
        DefaultTableModel tblmodel = (DefaultTableModel) table2.getModel();
        ((DefaultTableModel) table2.getModel()).setNumRows(0);
        tblmodel.setRowCount(0); // Clear existing data

        Stack<Office> emp = office1.getAlldata();
        for (Office office : emp) {
            Object[] rowData = {office.getId(), office.getName(), office.getPhone(), office.getQual(), office.getExp()};
            tblmodel.addRow(rowData);
        }
//        For clear all fiels
        Staffid.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        JOptionPane.showMessageDialog(this, "Data Successfully Deleted");
    }//GEN-LAST:event_StaffDeleteActionPerformed

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jLabel72MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel72MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel72MouseClicked

    private void PeonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeonAddActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(peonid.getText());
        String name = jTextField10.getText();
        String phone = temp2.getText();
        String qual = temp2.getText();
        String exp = temp2.getText();
        String cnic = jTextField13.getText();
        String salary = jTextField12.getText();
        String age = jTextField11.getText();

        Office off = new Office(id, name, phone, qual, exp, cnic, salary, age);
        office1.add(off);
//        Data Push To Table
        DefaultTableModel tblmodel = (DefaultTableModel) table3.getModel();
        ((DefaultTableModel) table3.getModel()).setNumRows(0);
        tblmodel.setRowCount(0); // Clear existing data

        Stack<Office> emp = office1.getAlldata();
        for (Office office : emp) {
            Object[] rowData = {office.getId(), office.getName(), office.getAge(),office.getSalary(),office.getCnic()};
            tblmodel.addRow(rowData);
        }
//        For clear all fiels
        peonid.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField13.setText("");
        JOptionPane.showMessageDialog(this, "Data Successfully Added");
    }//GEN-LAST:event_PeonAddActionPerformed

    private void PeonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeonUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRow = table3.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to update.");
            return;
        }
        int id = (int) table3.getValueAt(selectedRow, 0);
//      int id = Integer.parseInt(Employeid.getText());
        String name = jTextField10.getText();
        String phone = temp2.getText();
        String qual = temp2.getText();
        String exp = temp2.getText();
        String cnic = jTextField13.getText();
        String salary = jTextField12.getText();
        String age = jTextField11.getText();

        Office updatedoff = new Office(id, name, phone, qual, exp, cnic, salary, age);
        office1.update(id, updatedoff);
//        Data Push To Table
         DefaultTableModel tblmodel = (DefaultTableModel) table3.getModel();
        ((DefaultTableModel) table3.getModel()).setNumRows(0);
        tblmodel.setRowCount(0); // Clear existing data

        Stack<Office> emp = office1.getAlldata();
        for (Office office : emp) {
            Object[] rowData = {office.getId(), office.getName(), office.getAge(),office.getSalary(),office.getCnic()};
            tblmodel.addRow(rowData);
        }
//        For clear all fiels
        peonid.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField13.setText("");
        JOptionPane.showMessageDialog(this, "Data Successfully Updated");
    }//GEN-LAST:event_PeonUpdateActionPerformed

    private void table3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table3MouseClicked
        // TODO add your handling code here:
        int selectedRow = table3.getSelectedRow();
        if (selectedRow != -1) {
            int id = (int) table3.getValueAt(selectedRow, 0);
            String name = (String) table3.getValueAt(selectedRow, 1);
            String age = (String) table3.getValueAt(selectedRow, 2);
            String salary = (String) table3.getValueAt(selectedRow, 3);
            String cnic = (String) table3.getValueAt(selectedRow, 4);

            peonid.setText(String.valueOf(id));
            jTextField10.setText(name);
            jTextField11.setText(age);
            jTextField12.setText(salary);
            jTextField13.setText(cnic);
        }
    }//GEN-LAST:event_table3MouseClicked

    private void PeonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeonDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = table3.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to remove.");
            return;
        }

        int id = (int) table3.getValueAt(selectedRow, 0);
        office1.remove(id);
//        Data Push To Table
        DefaultTableModel tblmodel = (DefaultTableModel) table3.getModel();
        ((DefaultTableModel) table3.getModel()).setNumRows(0);
        tblmodel.setRowCount(0); // Clear existing data

        Stack<Office> emp = office1.getAlldata();
        for (Office office : emp) {
            Object[] rowData = {office.getId(), office.getName(), office.getAge(), office.getQual(), office.getExp()};
            tblmodel.addRow(rowData);
        }
//        For clear all fiels
        peonid.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField13.setText("");
        JOptionPane.showMessageDialog(this, "Data Successfully Deleted");
    }//GEN-LAST:event_PeonDeleteActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        int b=JOptionPane.showConfirmDialog(null, "DO you really want to Shoutdown the Application","Select",JOptionPane.YES_NO_OPTION);
        if(b==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel14MouseClicked

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Office_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Office_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Office_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Office_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Office_Management_System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EmployeeAdd;
    private javax.swing.JButton EmployeeDelete;
    private javax.swing.JButton EmployeeUpdate;
    private javax.swing.JTextField Employeid;
    private javax.swing.JPanel Hiddenpannel;
    private javax.swing.JButton PeonAdd;
    private javax.swing.JButton PeonDelete;
    private javax.swing.JButton PeonUpdate;
    private javax.swing.JButton StaffAdd;
    private javax.swing.JButton StaffDelete;
    private javax.swing.JButton StaffUpdate;
    private javax.swing.JTextField Staffid;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField peonid;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JTable table3;
    private javax.swing.JTextField temp;
    private javax.swing.JTextField temp1;
    private javax.swing.JTextField temp2;
    // End of variables declaration//GEN-END:variables
}
